global:
  gatewayApi:
    enabled: false
  hosts:
    domain: localhost
    https: false
  ingress:
    configureCertmanager: false
    tls:
      enabled: true
  redis:
    host: redis-master.gitlab.svc.cluster.local
  psql:
    host: postgresql.gitlab.svc.cluster.local
    password:
      secret: postgresql
  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-minio-secret
        key: connection

certmanager:
  install: false

certmanager-issuer:
  email: theoclaereboudt@gmail.com

nginx-ingress:
  enabled: false

prometheus:
  enabled: false

gitlab-runner:
  enabled: false

registry:
  enabled: false

gitlab:
  toolbox:
    enabled: false
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 100M
        memory: 900M
  sidekiq:
    resources:
      requests:
        cpu: 50M
        memory: 625M
  gitaly:
    resources:
      requests:
        cpu: 50M
        memory: 200M

minio:
  resources:
    requests:
      memory: 128Mi
