Vagrant.configure(2) do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.boot_timeout = 300
	# config.vm.box_url = REDACTED
	config.vm.define "tclaerebS" do |control|
		control.vm.hostname = "tclaerebS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |v|
			v.name = "tclaerebS"
			v.memory = 2048
			v.cpus = 2
			v.customize [
				"modifyvm", :id,
				"--cpuexecutioncap", "80"
			]
		end
		# config.vm.provision :shell, :inline => SHELL
		# SHELL
		control.vm.provision "shell", path: "./scripts/server.sh"
	end
	config.vm.define "tclaerebSW" do |control|
		control.vm.hostname = "tclaerebSW"
		control.vm.network "private_network", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |v|
			v.name = "tclaerebSW"
			v.memory = 2048
			v.cpus = 2
			v.customize [
				"modifyvm", :id,
				"--cpuexecutioncap", "80",
			]
		end
		# config.vm.provision "shell", inline: <<-SHELL
		# SHELL
		control.vm.provision "shell", path: "./scripts/agent.sh"
	end
end
