Vagrant.configure(2) do |config|
	config.vm.box = "debian/bookworm64"
	# config.vm.box_url = REDACTED
	config.vm.define "tclaerebS" do |control|
		control.vm.hostname = "tclaerebS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |v|
			v.customize [
				"modifyvm", :id,
				"--name", "tclaerebS",
				"--memory", "512",
				"--cpus", "1",
			]
		end
		# config.vm.provision :shell, :inline => SHELL
		# SHELL
		control.vm.provision "shell", path: "./scripts/server.sh"
	end
	config.vm.define "tclaerebSW" do |control|
		control.vm.hostname = "tclaerebSW"
		control.vm.network "private_network", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |v|
		v.customize [
			"modifyvm", :id,
			"--name", "tclaerebSW",
			"--memory", "512",
			"--cpus", "1",
			]
		end
		# config.vm.provision "shell", inline: <<-SHELL
		# SHELL
		control.vm.provision "shell", path: "./scripts/server2.sh"
	end
end
