Vagrant.configure(2) do |config|
	vm_name = "tclaerebS"

	config.vm.box = "debian/bookworm64"

	config.vm.define vm_name do |control|
		control.vm.hostname = vm_name

		control.vm.network "private_network", ip: "192.168.56.110"

		control.vm.provider "virtualbox" do |v|
			v.name = vm_name
			v.memory = 2048
			v.cpus = 2
			v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
		end

		control.vm.provision "shell", path: "./scripts/server.sh"
	end
end
